### ISSUE TITLE
[Feature Fix] - Add TabBar width automatically

### ISSUE THREAD

**Issue by Derewith** [Oksana96/animated-tabbar-react-native#1]
**The code is awesome!**
Just and addition to update in tabbar.js line 40 
from
`const tabWidth = dimensions.width / 4;` 
to 
`const tabWidth = dimensions.width / Number(navigation.state.routes.length);`

Now if the router has more or less routes, the animated tab-bar won't bug.

**Comment by Oksana96** [comment]
Thank you! I didn't think about it! I fixed the issue
